version: "3.7"

services:
    prometheus:
        image: prom/prometheus:latest
        # ports:
        #     - 9090:9090
        volumes:
            - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./data/prometheus/data:/prometheus
    grafana:
        image: grafana/grafana:latest
        volumes:
            - ./data/grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./data/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./data/grafana/data:/var/lib/grafana
    mangle:
        build:
            context: ./mangle
        # ports:
        #     - 9123:9123
        volumes:
            - ~/state.json:/state.json
    caddy:
        image: caddy:alpine
        volumes:
            - ./data/caddy/data:/data
            - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
        ports:
            - 80:80
            - 443:443
